services:
  dev-mongo:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3000'
    ports:
      - "8091:3000"  # Puedes modificar el puerto según tus necesidades
    volumes:
      - ./storage/uploads:/usr/src/app/storage/uploads
    restart: always
